using DomainLayer.Entities.Concrete;
using DomainLayer.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InfrastructureLayer.Configurations
{
    public class ProductConfig : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> builder)
        {
            builder.HasData(
 new Product { ProductId = 1, ProductName = "Plastic Wrap", Description = "Keep your food fresh.", Price = 0.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 1 },
new Product { ProductId = 2, ProductName = "Plastic Food Containers", Description = "Microwave and dishwasher safe.", Price = 1.20m, Material = Material.Polypropylene, IsActive = true, CategoryId = 1 },
new Product { ProductId = 3, ProductName = "Food Storage Bags", Description = "Ideal for preserving food.", Price = 0.15m, Material = Material.Polyethylene, IsActive = true, CategoryId = 1 },
new Product { ProductId = 4, ProductName = "Foil Containers", Description = "Perfect for takeout.", Price = 0.75m, Material = Material.Aluminum, IsActive = true, CategoryId = 1 },
new Product { ProductId = 5, ProductName = "Plastic Wrap Dispenser", Description = "Easy to use for packaging.", Price = 3.50m, Material = Material.Plastic, IsActive = true, CategoryId = 1 },
new Product { ProductId = 6, ProductName = "Sealable Bags", Description = "For storing leftovers.", Price = 0.25m, Material = Material.Polyethylene, IsActive = true, CategoryId = 1 },
new Product { ProductId = 7, ProductName = "Microwavable Containers", Description = "For heating food safely.", Price = 1.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 1 },
new Product { ProductId = 8, ProductName = "Takeout Boxes", Description = "For quick meals.", Price = 0.40m, Material = Material.Paper, IsActive = true, CategoryId = 1 },
new Product { ProductId = 9, ProductName = "Bamboo Food Containers", Description = "Eco-friendly option.", Price = 2.00m, Material = Material.Bioplastics, IsActive = true, CategoryId = 1 },
new Product { ProductId = 10, ProductName = "Plastic Food Storage Bins", Description = "Great for organization.", Price = 1.75m, Material = Material.Polypropylene, IsActive = true, CategoryId = 1 },
new Product { ProductId = 11, ProductName = "Plastic Bottles", Description = "Perfect for beverages.", Price = 0.30m, Material = Material.Polyethylene, IsActive = true, CategoryId = 2 },
new Product { ProductId = 12, ProductName = "Aluminum Cans", Description = "For soft drinks.", Price = 0.50m, Material = Material.Aluminum, IsActive = true, CategoryId = 2 },
new Product { ProductId = 13, ProductName = "Plastic Cups", Description = "Disposable and convenient.", Price = 0.10m, Material = Material.Polypropylene, IsActive = true, CategoryId = 2 },
new Product { ProductId = 14, ProductName = "Glass Bottles", Description = "Reusable and recyclable.", Price = 1.00m, Material = Material.Glass, IsActive = true, CategoryId = 2 },
new Product { ProductId = 15, ProductName = "Drink Pouches", Description = "For juice and smoothies.", Price = 0.25m, Material = Material.Polyethylene, IsActive = true, CategoryId = 2 },
new Product { ProductId = 16, ProductName = "Tetra Pak Containers", Description = "For long shelf life.", Price = 0.75m, Material = Material.Composite, IsActive = true, CategoryId = 2 },
new Product { ProductId = 17, ProductName = "Reusable Water Bottles", Description = "Eco-friendly choice.", Price = 1.50m, Material = Material.StainlessSteel, IsActive = true, CategoryId = 2 },
new Product { ProductId = 18, ProductName = "Coffee Cups", Description = "Ideal for hot beverages.", Price = 0.60m, Material = Material.Paper, IsActive = true, CategoryId = 2 },
new Product { ProductId = 19, ProductName = "Plastic Straws", Description = "Convenient for drinks.", Price = 0.05m, Material = Material.Polypropylene, IsActive = true, CategoryId = 2 },
new Product { ProductId = 20, ProductName = "Wine Bottles", Description = "For storing wine.", Price = 1.25m, Material = Material.Glass, IsActive = true, CategoryId = 2 },
new Product { ProductId = 21, ProductName = "Plastic Cosmetic Jars", Description = "Ideal for creams.", Price = 1.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 3 },
new Product { ProductId = 22, ProductName = "Acrylic Cosmetic Containers", Description = "Stylish and durable.", Price = 2.00m, Material = Material.Acrylic, IsActive = true, CategoryId = 3 },
new Product { ProductId = 23, ProductName = "Roll-On Bottles", Description = "Perfect for oils and perfumes.", Price = 0.80m, Material = Material.Polyethylene, IsActive = true, CategoryId = 3 },
new Product { ProductId = 24, ProductName = "Lip Balm Tubes", Description = "For lip care products.", Price = 0.20m, Material = Material.Polypropylene, IsActive = true, CategoryId = 3 },
new Product { ProductId = 25, ProductName = "Plastic Spray Bottles", Description = "For perfumes and sprays.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 3 },
new Product { ProductId = 26, ProductName = "Glass Jars", Description = "Ideal for skincare products.", Price = 1.75m, Material = Material.Glass, IsActive = true, CategoryId = 3 },
new Product { ProductId = 27, ProductName = "Cosmetic Bags", Description = "For organization.", Price = 0.90m, Material = Material.Canvas, IsActive = true, CategoryId = 3 },
new Product { ProductId = 28, ProductName = "Plastic Compacts", Description = "For makeup products.", Price = 1.20m, Material = Material.Polypropylene, IsActive = true, CategoryId = 3 },
new Product { ProductId = 29, ProductName = "Face Mask Packaging", Description = "Ideal for facial masks.", Price = 0.50m, Material = Material.Bioplastics, IsActive = true, CategoryId = 3 },
new Product { ProductId = 30, ProductName = "Eco-friendly Cosmetic Packaging", Description = "Sustainable choices.", Price = 2.50m, Material = Material.Bioplastics, IsActive = true, CategoryId = 3 },
new Product { ProductId = 31, ProductName = "Medical Blister Packs", Description = "For safe medicine storage.", Price = 0.80m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 4 },
new Product { ProductId = 32, ProductName = "Surgical Packs", Description = "Sterile and secure.", Price = 3.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 4 },
new Product { ProductId = 33, ProductName = "Medical Containers", Description = "For pharmaceutical storage.", Price = 2.00m, Material = Material.Polypropylene, IsActive = true, CategoryId = 4 },
new Product { ProductId = 34, ProductName = "Thermal Medical Bags", Description = "For temperature-sensitive products.", Price = 1.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 4 },
new Product { ProductId = 35, ProductName = "IV Bags", Description = "For intravenous therapy.", Price = 0.40m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 4 },
new Product { ProductId = 36, ProductName = "Sample Collection Tubes", Description = "For lab samples.", Price = 0.30m, Material = Material.Polypropylene, IsActive = true, CategoryId = 4 },
new Product { ProductId = 37, ProductName = "Pill Bottles", Description = "For medication storage.", Price = 0.60m, Material = Material.Polyethylene, IsActive = true, CategoryId = 4 },
new Product { ProductId = 38, ProductName = "Syringe Packaging", Description = "Safe storage for syringes.", Price = 0.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 4 },
new Product { ProductId = 39, ProductName = "Medical Labels", Description = "For identifying products.", Price = 0.10m, Material = Material.Paper, IsActive = true, CategoryId = 4 },
new Product { ProductId = 40, ProductName = "Biohazard Bags", Description = "For hazardous waste.", Price = 0.20m, Material = Material.Polyethylene, IsActive = true, CategoryId = 4 },
new Product { ProductId = 41, ProductName = "Pharmaceutical Bottles", Description = "For tablets and liquids.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 5 },
new Product { ProductId = 42, ProductName = "Child-resistant Caps", Description = "For safety.", Price = 0.15m, Material = Material.Polypropylene, IsActive = true, CategoryId = 5 },
new Product { ProductId = 43, ProductName = "Pill Organizers", Description = "For medication management.", Price = 2.00m, Material = Material.Polypropylene, IsActive = true, CategoryId = 5 },
new Product { ProductId = 44, ProductName = "Labeling Machines", Description = "For labeling products.", Price = 500.00m, Material = Material.Metal, IsActive = true, CategoryId = 5 },
new Product { ProductId = 45, ProductName = "Syringe Packaging", Description = "For syringes.", Price = 0.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 5 },
new Product { ProductId = 46, ProductName = "Blister Card Packaging", Description = "For pharmaceuticals.", Price = 0.60m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 5 },
new Product { ProductId = 47, ProductName = "Pharmaceutical Sachets", Description = "For single-dose medications.", Price = 0.25m, Material = Material.Polyethylene, IsActive = true, CategoryId = 5 },
new Product { ProductId = 48, ProductName = "IV Bags", Description = "For intravenous medications.", Price = 0.40m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 5 },
new Product { ProductId = 49, ProductName = "Medication Guides", Description = "For informing patients.", Price = 0.10m, Material = Material.Paper, IsActive = true, CategoryId = 5 },
new Product { ProductId = 50, ProductName = "Prescription Bags", Description = "For dispensing medications.", Price = 0.15m, Material = Material.Paper, IsActive = true, CategoryId = 5 },
new Product { ProductId = 51, ProductName = "Flexible Pouches", Description = "For various products.", Price = 0.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 6 },
new Product { ProductId = 52, ProductName = "Stand-up Pouches", Description = "Convenient for storage.", Price = 0.75m, Material = Material.Polypropylene, IsActive = true, CategoryId = 6 },
new Product { ProductId = 53, ProductName = "Flexible Plastic Bags", Description = "For easy carrying.", Price = 0.20m, Material = Material.Polyethylene, IsActive = true, CategoryId = 6 },
new Product { ProductId = 54, ProductName = "Shrink Bags", Description = "For tight packaging.", Price = 0.30m, Material = Material.Polyethylene, IsActive = true, CategoryId = 6 },
new Product { ProductId = 55, ProductName = "Vacuum Bags", Description = "For preserving food.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 6 },
new Product { ProductId = 56, ProductName = "Rollstock Film", Description = "For custom packaging.", Price = 0.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 6 },
new Product { ProductId = 57, ProductName = "Food Pouches", Description = "For snacks and meals.", Price = 0.40m, Material = Material.Polyethylene, IsActive = true, CategoryId = 6 },
new Product { ProductId = 58, ProductName = "Gusseted Bags", Description = "For bulk items.", Price = 0.60m, Material = Material.Polypropylene, IsActive = true, CategoryId = 6 },
new Product { ProductId = 59, ProductName = "Zipper Bags", Description = "For secure closure.", Price = 0.25m, Material = Material.Polyethylene, IsActive = true, CategoryId = 6 },
new Product { ProductId = 60, ProductName = "Tamper-evident Bags", Description = "For security.", Price = 0.30m, Material = Material.Polyethylene, IsActive = true, CategoryId = 6 },
new Product { ProductId = 61, ProductName = "Rigid Plastic Containers", Description = "Durable and versatile.", Price = 1.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 7 },
new Product { ProductId = 62, ProductName = "Glass Jars", Description = "For various products.", Price = 2.00m, Material = Material.Glass, IsActive = true, CategoryId = 7 },
new Product { ProductId = 63, ProductName = "Metal Cans", Description = "For food and beverages.", Price = 0.80m, Material = Material.Metal, IsActive = true, CategoryId = 7 },
new Product { ProductId = 64, ProductName = "Plastic Buckets", Description = "For bulk storage.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 7 },
new Product { ProductId = 65, ProductName = "Rigid Trays", Description = "For displaying products.", Price = 0.60m, Material = Material.Polypropylene, IsActive = true, CategoryId = 7 },
new Product { ProductId = 66, ProductName = "Plastic Crates", Description = "For transportation.", Price = 2.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 7 },
new Product { ProductId = 67, ProductName = "Metal Storage Containers", Description = "For industrial use.", Price = 4.00m, Material = Material.Metal, IsActive = true, CategoryId = 7 },
new Product { ProductId = 68, ProductName = "Plastic Storage Bins", Description = "For organization.", Price = 1.75m, Material = Material.Polypropylene, IsActive = true, CategoryId = 7 },
new Product { ProductId = 69, ProductName = "Thermal Insulated Containers", Description = "For temperature control.", Price = 3.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 7 },
new Product { ProductId = 70, ProductName = "Heavy-Duty Tubs", Description = "For industrial applications.", Price = 5.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 7 },
new Product { ProductId = 71, ProductName = "LDPE Plastic Bags", Description = "Lightweight and versatile.", Price = 0.10m, Material = Material.Polyethylene, IsActive = true, CategoryId = 8 },
new Product { ProductId = 72, ProductName = "HDPE Grocery Bags", Description = "For shopping needs.", Price = 0.05m, Material = Material.Polyethylene, IsActive = true, CategoryId = 8 },
new Product { ProductId = 73, ProductName = "Biodegradable Bags", Description = "Eco-friendly choice.", Price = 0.15m, Material = Material.Bioplastics, IsActive = true, CategoryId = 8 },
new Product { ProductId = 74, ProductName = "Plastic Trash Bags", Description = "Durable and strong.", Price = 0.20m, Material = Material.Polyethylene, IsActive = true, CategoryId = 8 },
new Product { ProductId = 75, ProductName = "Reusable Shopping Bags", Description = "For sustainability.", Price = 1.00m, Material = Material.Canvas, IsActive = true, CategoryId = 8 },
new Product { ProductId = 76, ProductName = "Plastic Mailers", Description = "For shipping purposes.", Price = 0.30m, Material = Material.Polyethylene, IsActive = true, CategoryId = 8 },
new Product { ProductId = 77, ProductName = "Plastic Sandwich Bags", Description = "For lunch packing.", Price = 0.10m, Material = Material.Polyethylene, IsActive = true, CategoryId = 8 },
new Product { ProductId = 78, ProductName = "Plastic Ziplock Bags", Description = "For secure storage.", Price = 0.15m, Material = Material.Polyethylene, IsActive = true, CategoryId = 8 },
new Product { ProductId = 79, ProductName = "Plastic Retail Bags", Description = "For retail purposes.", Price = 0.05m, Material = Material.Polyethylene, IsActive = true, CategoryId = 8 },
new Product { ProductId = 80, ProductName = "Plastic Produce Bags", Description = "For fruits and vegetables.", Price = 0.07m, Material = Material.Polyethylene, IsActive = true, CategoryId = 8 },
new Product { ProductId = 81, ProductName = "Shrink Wrap Film", Description = "For secure packaging.", Price = 0.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 9 },
new Product { ProductId = 82, ProductName = "Shrink Bands", Description = "For tamper evidence.", Price = 0.20m, Material = Material.Polyethylene, IsActive = true, CategoryId = 9 },
new Product { ProductId = 83, ProductName = "Shrink Wrap Machine", Description = "For efficient packing.", Price = 300.00m, Material = Material.Metal, IsActive = true, CategoryId = 9 },
new Product { ProductId = 84, ProductName = "Shrink Wrap Sheets", Description = "For custom sizes.", Price = 0.30m, Material = Material.Polyethylene, IsActive = true, CategoryId = 9 },
new Product { ProductId = 85, ProductName = "PVC Shrink Wrap", Description = "For high clarity packaging.", Price = 0.40m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 9 },
new Product { ProductId = 86, ProductName = "Centerfold Shrink Film", Description = "For large items.", Price = 0.70m, Material = Material.Polyethylene, IsActive = true, CategoryId = 9 },
new Product { ProductId = 87, ProductName = "Shrink Wrap Rolls", Description = "For industrial use.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 9 },
new Product { ProductId = 88, ProductName = "Shrink Wrap Bags", Description = "For smaller items.", Price = 0.25m, Material = Material.Polyethylene, IsActive = true, CategoryId = 9 },
new Product { ProductId = 89, ProductName = "Shrink Wrap Labeling", Description = "For easy identification.", Price = 0.15m, Material = Material.Paper, IsActive = true, CategoryId = 9 },
new Product { ProductId = 90, ProductName = "Custom Shrink Wrap", Description = "For personalized packaging.", Price = 1.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 9 },
new Product { ProductId = 91, ProductName = "Blister Packaging Sheets", Description = "For product display.", Price = 0.50m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 10 },
new Product { ProductId = 92, ProductName = "Carded Blister Packs", Description = "For retail items.", Price = 1.00m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 10 },
new Product { ProductId = 93, ProductName = "Blister Packaging Machines", Description = "For efficient production.", Price = 500.00m, Material = Material.Metal, IsActive = true, CategoryId = 10 },
new Product { ProductId = 94, ProductName = "Custom Blister Packs", Description = "For personalized branding.", Price = 0.80m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 10 },
new Product { ProductId = 95, ProductName = "Blister Carding", Description = "For secure sealing.", Price = 0.60m, Material = Material.Paper, IsActive = true, CategoryId = 10 },
new Product { ProductId = 96, ProductName = "Clamshell Blister Packs", Description = "For easy opening.", Price = 1.20m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 10 },
new Product { ProductId = 97, ProductName = "Blister Packaging Trays", Description = "For multiple items.", Price = 0.70m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 10 },
new Product { ProductId = 98, ProductName = "Eco-friendly Blister Packs", Description = "Sustainable packaging.", Price = 1.50m, Material = Material.Bioplastics, IsActive = true, CategoryId = 10 },
new Product { ProductId = 99, ProductName = "Blister Packaging Inserts", Description = "For added protection.", Price = 0.40m, Material = Material.Paper, IsActive = true, CategoryId = 10 },
new Product { ProductId = 100, ProductName = "Pharmaceutical Blister Packs", Description = "For safe medication storage.", Price = 0.90m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 10 },
new Product { ProductId = 101, ProductName = "Thermoformed Containers", Description = "For food and retail.", Price = 0.70m, Material = Material.Polypropylene, IsActive = true, CategoryId = 11 },
new Product { ProductId = 102, ProductName = "Thermoformed Trays", Description = "For product display.", Price = 0.80m, Material = Material.Polypropylene, IsActive = true, CategoryId = 11 },
new Product { ProductId = 103, ProductName = "Thermoformed Blisters", Description = "For packaging small items.", Price = 0.60m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 11 },
new Product { ProductId = 104, ProductName = "Custom Thermoforming", Description = "For personalized products.", Price = 1.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 11 },
new Product { ProductId = 105, ProductName = "Thermoformed Packaging Machines", Description = "For production needs.", Price = 400.00m, Material = Material.Metal, IsActive = true, CategoryId = 11 },
new Product { ProductId = 106, ProductName = "Eco-friendly Thermoformed Packaging", Description = "Sustainable options.", Price = 1.25m, Material = Material.Bioplastics, IsActive = true, CategoryId = 11 },
new Product { ProductId = 107, ProductName = "Thermoformed Cups", Description = "For food service.", Price = 0.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 11 },
new Product { ProductId = 108, ProductName = "Thermoformed Lids", Description = "For secure sealing.", Price = 0.20m, Material = Material.Polypropylene, IsActive = true, CategoryId = 11 },
new Product { ProductId = 109, ProductName = "Thermoformed Clamshells", Description = "For easy opening.", Price = 0.90m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 11 },
new Product { ProductId = 110, ProductName = "Food Containers", Description = "For meal prep.", Price = 1.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 11 },
new Product { ProductId = 111, ProductName = "Vacuum Seal Bags", Description = "For food preservation.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 12 },
new Product { ProductId = 112, ProductName = "Vacuum Packing Machines", Description = "For easy sealing.", Price = 250.00m, Material = Material.Metal, IsActive = true, CategoryId = 12 },
new Product { ProductId = 113, ProductName = "Vacuum Seal Rolls", Description = "Custom sizes available.", Price = 0.80m, Material = Material.Polyethylene, IsActive = true, CategoryId = 12 },
new Product { ProductId = 114, ProductName = "Reusable Vacuum Bags", Description = "Eco-friendly option.", Price = 1.50m, Material = Material.Bioplastics, IsActive = true, CategoryId = 12 },
new Product { ProductId = 115, ProductName = "Heavy-Duty Vacuum Bags", Description = "For long-term storage.", Price = 1.20m, Material = Material.Polyethylene, IsActive = true, CategoryId = 12 },
new Product { ProductId = 116, ProductName = "Vacuum Food Canisters", Description = "For airtight storage.", Price = 2.50m, Material = Material.Plastic, IsActive = true, CategoryId = 12 },
new Product { ProductId = 117, ProductName = "Vacuum Sealer Accessories", Description = "For maintenance.", Price = 15.00m, Material = Material.Metal, IsActive = true, CategoryId = 12 },
new Product { ProductId = 118, ProductName = "Commercial Vacuum Bags", Description = "For business use.", Price = 2.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 12 },
new Product { ProductId = 119, ProductName = "Vacuum Seal Containers", Description = "For liquids.", Price = 3.00m, Material = Material.Plastic, IsActive = true, CategoryId = 12 },
new Product { ProductId = 120, ProductName = "Vacuum Bag Roll Dispenser", Description = "For convenient use.", Price = 10.00m, Material = Material.Metal, IsActive = true, CategoryId = 12 },
new Product { ProductId = 121, ProductName = "Standard Stretch Film", Description = "For securing pallets.", Price = 0.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 13 },
new Product { ProductId = 122, ProductName = "Hand Stretch Wrap", Description = "For manual use.", Price = 0.40m, Material = Material.Polyethylene, IsActive = true, CategoryId = 13 },
new Product { ProductId = 123, ProductName = "Machine Stretch Film", Description = "For automated packing.", Price = 0.60m, Material = Material.Polyethylene, IsActive = true, CategoryId = 13 },
new Product { ProductId = 124, ProductName = "Colored Stretch Film", Description = "For branding.", Price = 0.70m, Material = Material.Polyethylene, IsActive = true, CategoryId = 13 },
new Product { ProductId = 125, ProductName = "Heavy-Duty Stretch Film", Description = "For heavy loads.", Price = 0.90m, Material = Material.Polyethylene, IsActive = true, CategoryId = 13 },
new Product { ProductId = 126, ProductName = "Pre-Stretched Film", Description = "For ease of use.", Price = 0.80m, Material = Material.Polyethylene, IsActive = true, CategoryId = 13 },
new Product { ProductId = 127, ProductName = "Eco-Friendly Stretch Film", Description = "Sustainable option.", Price = 1.00m, Material = Material.Bioplastics, IsActive = true, CategoryId = 13 },
new Product { ProductId = 128, ProductName = "Stretch Film Dispenser", Description = "For easy handling.", Price = 15.00m, Material = Material.Metal, IsActive = true, CategoryId = 13 },
new Product { ProductId = 129, ProductName = "Bundling Stretch Film", Description = "For securing multiple items.", Price = 0.65m, Material = Material.Polyethylene, IsActive = true, CategoryId = 13 },
new Product { ProductId = 130, ProductName = "Pallet Wrap Film", Description = "For palletizing products.", Price = 0.75m, Material = Material.Polyethylene, IsActive = true, CategoryId = 13 },
new Product { ProductId = 131, ProductName = "PET Plastic Bottles", Description = "Lightweight and recyclable.", Price = 0.20m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 14 },
new Product { ProductId = 132, ProductName = "HDPE Bottles", Description = "Durable and safe.", Price = 0.25m, Material = Material.Polyethylene, IsActive = true, CategoryId = 14 },
new Product { ProductId = 133, ProductName = "Plastic Squeeze Bottles", Description = "For sauces and condiments.", Price = 0.30m, Material = Material.Polypropylene, IsActive = true, CategoryId = 14 },
new Product { ProductId = 134, ProductName = "Plastic Pump Bottles", Description = "For lotions and liquids.", Price = 0.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 14 },
new Product { ProductId = 135, ProductName = "Recyclable Plastic Bottles", Description = "Eco-friendly choice.", Price = 0.35m, Material = Material.Bioplastics, IsActive = true, CategoryId = 14 },
new Product { ProductId = 136, ProductName = "Plastic Beverage Bottles", Description = "For drinks and beverages.", Price = 0.15m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 14 },
new Product { ProductId = 137, ProductName = "Plastic Oil Bottles", Description = "For cooking oils.", Price = 0.40m, Material = Material.Polyethylene, IsActive = true, CategoryId = 14 },
new Product { ProductId = 138, ProductName = "Plastic Sports Bottles", Description = "For fitness enthusiasts.", Price = 0.60m, Material = Material.Polypropylene, IsActive = true, CategoryId = 14 },
new Product { ProductId = 139, ProductName = "Plastic Jars with Lids", Description = "For food storage.", Price = 1.00m, Material = Material.Polypropylene, IsActive = true, CategoryId = 14 },
new Product { ProductId = 140, ProductName = "Custom Labeled Plastic Bottles", Description = "Personalized branding.", Price = 0.80m, Material = Material.Polyethylene, IsActive = true, CategoryId = 14 },
new Product { ProductId = 141, ProductName = "Plastic Food Containers", Description = "For meal storage.", Price = 0.70m, Material = Material.Polypropylene, IsActive = true, CategoryId = 15 },
new Product { ProductId = 142, ProductName = "Plastic Storage Bins", Description = "For organization.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 15 },
new Product { ProductId = 143, ProductName = "Plastic Tupperware", Description = "For leftovers.", Price = 0.90m, Material = Material.Polypropylene, IsActive = true, CategoryId = 15 },
new Product { ProductId = 144, ProductName = "Plastic Takeout Containers", Description = "For food service.", Price = 0.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 15 },
new Product { ProductId = 145, ProductName = "Plastic Organizer Containers", Description = "For craft supplies.", Price = 0.60m, Material = Material.Polyethylene, IsActive = true, CategoryId = 15 },
new Product { ProductId = 146, ProductName = "Plastic Coolers", Description = "For transporting food and drinks.", Price = 2.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 15 },
new Product { ProductId = 147, ProductName = "Plastic Food Storage Jars", Description = "For bulk items.", Price = 1.20m, Material = Material.Polypropylene, IsActive = true, CategoryId = 15 },
new Product { ProductId = 148, ProductName = "Plastic Snack Containers", Description = "For snacks on the go.", Price = 0.80m, Material = Material.Polyethylene, IsActive = true, CategoryId = 15 },
new Product { ProductId = 149, ProductName = "Plastic Picnic Containers", Description = "For outdoor meals.", Price = 1.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 15 },
new Product { ProductId = 150, ProductName = "Stackable Plastic Containers", Description = "For efficient storage.", Price = 1.00m, Material = Material.Polypropylene, IsActive = true, CategoryId = 15 },
new Product { ProductId = 151, ProductName = "Plastic Bottle Caps", Description = "For secure closure.", Price = 0.05m, Material = Material.Polyethylene, IsActive = true, CategoryId = 16 },
new Product { ProductId = 152, ProductName = "Screw Caps", Description = "For bottles and jars.", Price = 0.10m, Material = Material.Polypropylene, IsActive = true, CategoryId = 16 },
new Product { ProductId = 153, ProductName = "Tamper-Evident Caps", Description = "For safety.", Price = 0.12m, Material = Material.Polypropylene, IsActive = true, CategoryId = 16 },
new Product { ProductId = 154, ProductName = "Flip Top Caps", Description = "For easy access.", Price = 0.15m, Material = Material.Polyethylene, IsActive = true, CategoryId = 16 },
new Product { ProductId = 155, ProductName = "Snap-On Caps", Description = "For convenience.", Price = 0.08m, Material = Material.Polypropylene, IsActive = true, CategoryId = 16 },
new Product { ProductId = 156, ProductName = "Pour Spouts", Description = "For easy dispensing.", Price = 0.20m, Material = Material.Polyethylene, IsActive = true, CategoryId = 16 },
new Product { ProductId = 157, ProductName = "Plastic Lids", Description = "For various containers.", Price = 0.18m, Material = Material.Polypropylene, IsActive = true, CategoryId = 16 },
new Product { ProductId = 158, ProductName = "Dispensing Caps", Description = "For liquid products.", Price = 0.25m, Material = Material.Polypropylene, IsActive = true, CategoryId = 16 },
new Product { ProductId = 159, ProductName = "Custom Printed Caps", Description = "For branding.", Price = 0.30m, Material = Material.Bioplastics, IsActive = true, CategoryId = 16 },
new Product { ProductId = 160, ProductName = "Child-Resistant Caps", Description = "For safety.", Price = 0.35m, Material = Material.Polyethylene, IsActive = true, CategoryId = 16 },
new Product { ProductId = 161, ProductName = "Plastic Forks", Description = "For parties and events.", Price = 0.02m, Material = Material.Polypropylene, IsActive = true, CategoryId = 17 },
new Product { ProductId = 162, ProductName = "Plastic Spoons", Description = "For easy serving.", Price = 0.02m, Material = Material.Polypropylene, IsActive = true, CategoryId = 17 },
new Product { ProductId = 163, ProductName = "Plastic Knives", Description = "For quick meals.", Price = 0.02m, Material = Material.Polypropylene, IsActive = true, CategoryId = 17 },
new Product { ProductId = 164, ProductName = "Disposable Plates", Description = "For outdoor dining.", Price = 0.05m, Material = Material.Polypropylene, IsActive = true, CategoryId = 17 },
new Product { ProductId = 165, ProductName = "Disposable Cups", Description = "For drinks and beverages.", Price = 0.05m, Material = Material.Polypropylene, IsActive = true, CategoryId = 17 },
new Product { ProductId = 166, ProductName = "Biodegradable Utensils", Description = "Eco-friendly choice.", Price = 0.10m, Material = Material.Bioplastics, IsActive = true, CategoryId = 17 },
new Product { ProductId = 167, ProductName = "Disposable Cutlery Sets", Description = "For convenience.", Price = 0.15m, Material = Material.Polypropylene, IsActive = true, CategoryId = 17 },
new Product { ProductId = 168, ProductName = "Plastic Serving Utensils", Description = "For serving food.", Price = 0.10m, Material = Material.Polypropylene, IsActive = true, CategoryId = 17 },
new Product { ProductId = 169, ProductName = "Compostable Utensils", Description = "For sustainable dining.", Price = 0.12m, Material = Material.Bioplastics, IsActive = true, CategoryId = 17 },
new Product { ProductId = 170, ProductName = "Disposable Straws", Description = "For drinks.", Price = 0.03m, Material = Material.Polypropylene, IsActive = true, CategoryId = 17 },
new Product { ProductId = 171, ProductName = "Clamshell Food Containers", Description = "For takeout and delivery.", Price = 0.80m, Material = Material.Polypropylene, IsActive = true, CategoryId = 18 },
new Product { ProductId = 172, ProductName = "Clamshell Packaging Trays", Description = "For product display.", Price = 0.60m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 18 },
new Product { ProductId = 173, ProductName = "Eco-Friendly Clamshells", Description = "Sustainable option.", Price = 1.00m, Material = Material.Bioplastics, IsActive = true, CategoryId = 18 },
new Product { ProductId = 174, ProductName = "Clamshell Packaging Boxes", Description = "For retail products.", Price = 0.90m, Material = Material.Polypropylene, IsActive = true, CategoryId = 18 },
new Product { ProductId = 175, ProductName = "Clear Clamshells", Description = "For visibility.", Price = 0.70m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 18 },
new Product { ProductId = 176, ProductName = "Plastic Clamshell Containers", Description = "For snacks and meals.", Price = 0.75m, Material = Material.Polypropylene, IsActive = true, CategoryId = 18 },
new Product { ProductId = 177, ProductName = "Clamshells with Inserts", Description = "For added protection.", Price = 1.10m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 18 },
new Product { ProductId = 178, ProductName = "Custom Clamshell Packaging", Description = "For branding.", Price = 1.50m, Material = Material.Bioplastics, IsActive = true, CategoryId = 18 },
new Product { ProductId = 179, ProductName = "Clamshell Packaging for Electronics", Description = "For gadgets.", Price = 2.00m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 18 },
new Product { ProductId = 180, ProductName = "Reusable Clamshells", Description = "For eco-friendly use.", Price = 1.25m, Material = Material.Bioplastics, IsActive = true, CategoryId = 18 },
new Product { ProductId = 181, ProductName = "Plastic Film Rolls", Description = "For wrapping products.", Price = 0.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 19 },
new Product { ProductId = 182, ProductName = "Stretch Film Rolls", Description = "For pallet wrapping.", Price = 0.60m, Material = Material.Polyethylene, IsActive = true, CategoryId = 19 },
new Product { ProductId = 183, ProductName = "Shrink Film Rolls", Description = "For tight packaging.", Price = 0.70m, Material = Material.Polyethylene, IsActive = true, CategoryId = 19 },
new Product { ProductId = 184, ProductName = "Barrier Film", Description = "For moisture protection.", Price = 0.80m, Material = Material.Polyethylene, IsActive = true, CategoryId = 19 },
new Product { ProductId = 185, ProductName = "Heavy-Duty Film", Description = "For industrial use.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 19 },
new Product { ProductId = 186, ProductName = "Polypropylene Film", Description = "For clear packaging.", Price = 0.90m, Material = Material.Polypropylene, IsActive = true, CategoryId = 19 },
new Product { ProductId = 187, ProductName = "Biodegradable Film", Description = "For sustainable packaging.", Price = 1.20m, Material = Material.Bioplastics, IsActive = true, CategoryId = 19 },
new Product { ProductId = 188, ProductName = "Film for Food Packaging", Description = "For food safety.", Price = 0.75m, Material = Material.Polyethylene, IsActive = true, CategoryId = 19 },
new Product { ProductId = 189, ProductName = "Colored Film", Description = "For branding purposes.", Price = 0.85m, Material = Material.Polyethylene, IsActive = true, CategoryId = 19 },
new Product { ProductId = 190, ProductName = "Custom Printed Film", Description = "For marketing.", Price = 1.50m, Material = Material.Bioplastics, IsActive = true, CategoryId = 19 },
new Product { ProductId = 191, ProductName = "Injection Molded Containers", Description = "For food and retail.", Price = 1.00m, Material = Material.Polypropylene, IsActive = true, CategoryId = 20 },
new Product { ProductId = 192, ProductName = "Injection Molded Trays", Description = "For product display.", Price = 0.80m, Material = Material.Polypropylene, IsActive = true, CategoryId = 20 },
new Product { ProductId = 193, ProductName = "Plastic Injection Molded Parts", Description = "For various applications.", Price = 1.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 20 },
new Product { ProductId = 194, ProductName = "Custom Injection Molding", Description = "For tailored solutions.", Price = 2.00m, Material = Material.Polypropylene, IsActive = true, CategoryId = 20 },
new Product { ProductId = 195, ProductName = "Injection Molded Packaging Machines", Description = "For production needs.", Price = 600.00m, Material = Material.Metal, IsActive = true, CategoryId = 20 },
new Product { ProductId = 196, ProductName = "Injection Molded Caps", Description = "For secure sealing.", Price = 0.30m, Material = Material.Polypropylene, IsActive = true, CategoryId = 20 },
new Product { ProductId = 197, ProductName = "Injection Molded Lids", Description = "For various containers.", Price = 0.25m, Material = Material.Polypropylene, IsActive = true, CategoryId = 20 },
new Product { ProductId = 198, ProductName = "Injection Molded Clamshells", Description = "For secure packaging.", Price = 1.00m, Material = Material.Polypropylene, IsActive = true, CategoryId = 20 },
new Product { ProductId = 199, ProductName = "Injection Molded Jars", Description = "For bulk storage.", Price = 1.20m, Material = Material.Polypropylene, IsActive = true, CategoryId = 20 },
new Product { ProductId = 200, ProductName = "Custom Injection Molded Products", Description = "For unique solutions.", Price = 2.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 20 },
new Product { ProductId = 201, ProductName = "Clear PET Bottles", Description = "Ideal for beverages.", Price = 0.25m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 21 },
new Product { ProductId = 202, ProductName = "Colored PET Bottles", Description = "For juices and sauces.", Price = 0.30m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 21 },
new Product { ProductId = 203, ProductName = "PET Bottle with Cap", Description = "Includes secure cap.", Price = 0.28m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 21 },
new Product { ProductId = 204, ProductName = "Recyclable PET Bottles", Description = "Environmentally friendly.", Price = 0.26m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 21 },
new Product { ProductId = 205, ProductName = "PET Bottles for Cosmetics", Description = "For lotions and creams.", Price = 0.35m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 21 },
new Product { ProductId = 206, ProductName = "Custom Labeled PET Bottles", Description = "Perfect for branding.", Price = 0.40m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 21 },
new Product { ProductId = 207, ProductName = "PET Bottles with Handles", Description = "For easy carrying.", Price = 0.50m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 21 },
new Product { ProductId = 208, ProductName = "Bulk PET Bottles", Description = "For wholesale orders.", Price = 0.20m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 21 },
new Product { ProductId = 209, ProductName = "PET Sports Bottles", Description = "For athletes and fitness.", Price = 0.45m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 21 },
new Product { ProductId = 210, ProductName = "PET Juice Bottles", Description = "For fresh juices.", Price = 0.32m, Material = Material.PolyethyleneTerephthalate, IsActive = true, CategoryId = 21 },

new Product { ProductId = 211, ProductName = "HDPE Storage Containers", Description = "For various storage needs.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 22 },
new Product { ProductId = 212, ProductName = "HDPE Chemical Containers", Description = "For safe storage of chemicals.", Price = 1.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 22 },
new Product { ProductId = 213, ProductName = "HDPE Paint Containers", Description = "For paint and coatings.", Price = 1.20m, Material = Material.Polyethylene, IsActive = true, CategoryId = 22 },
new Product { ProductId = 214, ProductName = "HDPE Bulk Containers", Description = "For large quantities.", Price = 2.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 22 },
new Product { ProductId = 215, ProductName = "HDPE Jugs", Description = "For liquids and powders.", Price = 0.90m, Material = Material.Polyethylene, IsActive = true, CategoryId = 22 },
new Product { ProductId = 216, ProductName = "HDPE Food Containers", Description = "For food storage.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 22 },
new Product { ProductId = 217, ProductName = "HDPE Buckets", Description = "For various uses.", Price = 1.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 22 },
new Product { ProductId = 218, ProductName = "HDPE Shipping Containers", Description = "For safe transport.", Price = 2.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 22 },
new Product { ProductId = 219, ProductName = "Recyclable HDPE Containers", Description = "Eco-friendly option.", Price = 1.10m, Material = Material.Polyethylene, IsActive = true, CategoryId = 22 },
new Product { ProductId = 220, ProductName = "Custom HDPE Containers", Description = "Tailored to your needs.", Price = 2.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 22 },

new Product { ProductId = 221, ProductName = "LDPE Grocery Bags", Description = "For shopping needs.", Price = 0.05m, Material = Material.LowDensityPolyethylene, IsActive = true, CategoryId = 23 },
new Product { ProductId = 222, ProductName = "LDPE Trash Bags", Description = "For waste disposal.", Price = 0.10m, Material = Material.LowDensityPolyethylene, IsActive = true, CategoryId = 23 },
new Product { ProductId = 223, ProductName = "LDPE Freezer Bags", Description = "For food storage.", Price = 0.15m, Material = Material.LowDensityPolyethylene, IsActive = true, CategoryId = 23 },
new Product { ProductId = 224, ProductName = "LDPE Sandwich Bags", Description = "For lunch packing.", Price = 0.08m, Material = Material.LowDensityPolyethylene, IsActive = true, CategoryId = 23 },
new Product { ProductId = 225, ProductName = "LDPE Bulk Bags", Description = "For large items.", Price = 0.25m, Material = Material.LowDensityPolyethylene, IsActive = true, CategoryId = 23 },
new Product { ProductId = 226, ProductName = "LDPE Reusable Bags", Description = "Eco-friendly option.", Price = 0.20m, Material = Material.LowDensityPolyethylene, IsActive = true, CategoryId = 23 },
new Product { ProductId = 227, ProductName = "LDPE Barrier Bags", Description = "For moisture protection.", Price = 0.30m, Material = Material.LowDensityPolyethylene, IsActive = true, CategoryId = 23 },
new Product { ProductId = 228, ProductName = "LDPE Mailing Bags", Description = "For shipping products.", Price = 0.12m, Material = Material.LowDensityPolyethylene, IsActive = true, CategoryId = 23 },
new Product { ProductId = 229, ProductName = "Custom LDPE Bags", Description = "For branding.", Price = 0.18m, Material = Material.LowDensityPolyethylene, IsActive = true, CategoryId = 23 },
new Product { ProductId = 230, ProductName = "LDPE Packaging Bags", Description = "For various uses.", Price = 0.22m, Material = Material.LowDensityPolyethylene, IsActive = true, CategoryId = 23 },

new Product { ProductId = 231, ProductName = "Polypropylene Bags", Description = "Durable and lightweight.", Price = 0.20m, Material = Material.Polypropylene, IsActive = true, CategoryId = 24 },
new Product { ProductId = 232, ProductName = "Polypropylene Containers", Description = "For food and retail.", Price = 1.00m, Material = Material.Polypropylene, IsActive = true, CategoryId = 24 },
new Product { ProductId = 233, ProductName = "Polypropylene Film", Description = "For packaging needs.", Price = 0.50m, Material = Material.Polypropylene, IsActive = true, CategoryId = 24 },
new Product { ProductId = 234, ProductName = "Polypropylene Trays", Description = "For product display.", Price = 0.80m, Material = Material.Polypropylene, IsActive = true, CategoryId = 24 },
new Product { ProductId = 235, ProductName = "Polypropylene Straps", Description = "For securing packages.", Price = 0.30m, Material = Material.Polypropylene, IsActive = true, CategoryId = 24 },
new Product { ProductId = 236, ProductName = "Polypropylene Cups", Description = "For drinks.", Price = 0.12m, Material = Material.Polypropylene, IsActive = true, CategoryId = 24 },
new Product { ProductId = 237, ProductName = "Polypropylene Bags with Zipper", Description = "For easy sealing.", Price = 0.25m, Material = Material.Polypropylene, IsActive = true, CategoryId = 24 },
new Product { ProductId = 238, ProductName = "Custom Polypropylene Packaging", Description = "Tailored to your needs.", Price = 0.40m, Material = Material.Polypropylene, IsActive = true, CategoryId = 24 },
new Product { ProductId = 239, ProductName = "Polypropylene Pouches", Description = "For food storage.", Price = 0.18m, Material = Material.Polypropylene, IsActive = true, CategoryId = 24 },
new Product { ProductId = 240, ProductName = "Polypropylene Labels", Description = "For product information.", Price = 0.10m, Material = Material.Polypropylene, IsActive = true, CategoryId = 24 },

new Product { ProductId = 241, ProductName = "Polystyrene Foam Containers", Description = "For hot food.", Price = 0.30m, Material = Material.Polystyrene, IsActive = true, CategoryId = 25 },
new Product { ProductId = 242, ProductName = "Polystyrene Cups", Description = "For beverages.", Price = 0.15m, Material = Material.Polystyrene, IsActive = true, CategoryId = 25 },
new Product { ProductId = 243, ProductName = "Polystyrene Trays", Description = "For display and packaging.", Price = 0.20m, Material = Material.Polystyrene, IsActive = true, CategoryId = 25 },
new Product { ProductId = 244, ProductName = "Polystyrene Clamshells", Description = "For food and products.", Price = 0.25m, Material = Material.Polystyrene, IsActive = true, CategoryId = 25 },
new Product { ProductId = 245, ProductName = "Recyclable Polystyrene Packaging", Description = "Eco-friendly choice.", Price = 0.35m, Material = Material.Polystyrene, IsActive = true, CategoryId = 25 },
new Product { ProductId = 246, ProductName = "Polystyrene Food Containers", Description = "For takeout meals.", Price = 0.40m, Material = Material.Polystyrene, IsActive = true, CategoryId = 25 },
new Product { ProductId = 247, ProductName = "Polystyrene Deli Containers", Description = "For deli foods.", Price = 0.50m, Material = Material.Polystyrene, IsActive = true, CategoryId = 25 },
new Product { ProductId = 248, ProductName = "Polystyrene Sandwich Containers", Description = "For sandwiches.", Price = 0.30m, Material = Material.Polystyrene, IsActive = true, CategoryId = 25 },
new Product { ProductId = 249, ProductName = "Custom Polystyrene Packaging", Description = "For branding.", Price = 0.45m, Material = Material.Polystyrene, IsActive = true, CategoryId = 25 },
new Product { ProductId = 250, ProductName = "Polystyrene Lids", Description = "For various containers.", Price = 0.20m, Material = Material.Polystyrene, IsActive = true, CategoryId = 25 },

new Product { ProductId = 251, ProductName = "PVC Shrink Wrap", Description = "For tight sealing.", Price = 0.30m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 26 },
new Product { ProductId = 252, ProductName = "PVC Blister Packs", Description = "For product visibility.", Price = 0.50m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 26 },
new Product { ProductId = 253, ProductName = "PVC Pipe and Fittings", Description = "For plumbing needs.", Price = 2.00m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 26 },
new Product { ProductId = 254, ProductName = "PVC Containers", Description = "For various applications.", Price = 1.50m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 26 },
new Product { ProductId = 255, ProductName = "Custom PVC Packaging", Description = "Tailored for your needs.", Price = 1.00m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 26 },
new Product { ProductId = 256, ProductName = "PVC Shrink Sleeves", Description = "For labeling.", Price = 0.25m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 26 },
new Product { ProductId = 257, ProductName = "PVC Packaging Tape", Description = "For sealing packages.", Price = 0.15m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 26 },
new Product { ProductId = 258, ProductName = "PVC Protective Covers", Description = "For safeguarding items.", Price = 0.40m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 26 },
new Product { ProductId = 259, ProductName = "PVC Tarpaulins", Description = "For outdoor use.", Price = 1.80m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 26 },
new Product { ProductId = 260, ProductName = "PVC Labels", Description = "For product information.", Price = 0.10m, Material = Material.PolyvinylChloride, IsActive = true, CategoryId = 26 },

new Product { ProductId = 261, ProductName = "Biodegradable Bags", Description = "For eco-friendly use.", Price = 0.10m, Material = Material.Bioplastics, IsActive = true, CategoryId = 27 },
new Product { ProductId = 262, ProductName = "Biodegradable Containers", Description = "For food storage.", Price = 0.50m, Material = Material.Bioplastics, IsActive = true, CategoryId = 27 },
new Product { ProductId = 263, ProductName = "Biodegradable Utensils", Description = "For sustainable dining.", Price = 0.12m, Material = Material.Bioplastics, IsActive = true, CategoryId = 27 },
new Product { ProductId = 264, ProductName = "Biodegradable Packaging Film", Description = "For wrapping products.", Price = 0.75m, Material = Material.Bioplastics, IsActive = true, CategoryId = 27 },
new Product { ProductId = 265, ProductName = "Compostable Bags", Description = "For waste disposal.", Price = 0.15m, Material = Material.Bioplastics, IsActive = true, CategoryId = 27 },
new Product { ProductId = 266, ProductName = "Compostable Containers", Description = "For food and more.", Price = 0.50m, Material = Material.Bioplastics, IsActive = true, CategoryId = 27 },
new Product { ProductId = 267, ProductName = "Biodegradable Straws", Description = "For drinks.", Price = 0.08m, Material = Material.Bioplastics, IsActive = true, CategoryId = 27 },
new Product { ProductId = 268, ProductName = "Compostable Utensils", Description = "For dining needs.", Price = 0.10m, Material = Material.Bioplastics, IsActive = true, CategoryId = 27 },
new Product { ProductId = 269, ProductName = "Biodegradable Food Wrap", Description = "For fresh food storage.", Price = 0.20m, Material = Material.Bioplastics, IsActive = true, CategoryId = 27 },
new Product { ProductId = 270, ProductName = "Custom Biodegradable Packaging", Description = "For branding.", Price = 0.30m, Material = Material.Bioplastics, IsActive = true, CategoryId = 27 },

new Product { ProductId = 271, ProductName = "Compostable Bags", Description = "Eco-friendly for waste.", Price = 0.15m, Material = Material.Bioplastics, IsActive = true, CategoryId = 28 },
new Product { ProductId = 272, ProductName = "Compostable Plates", Description = "For dining needs.", Price = 0.25m, Material = Material.Bioplastics, IsActive = true, CategoryId = 28 },
new Product { ProductId = 273, ProductName = "Compostable Containers", Description = "For food storage.", Price = 0.50m, Material = Material.Bioplastics, IsActive = true, CategoryId = 28 },
new Product { ProductId = 274, ProductName = "Compostable Cutlery", Description = "For dining use.", Price = 0.12m, Material = Material.Bioplastics, IsActive = true, CategoryId = 28 },
new Product { ProductId = 275, ProductName = "Compostable Straws", Description = "For drinks.", Price = 0.10m, Material = Material.Bioplastics, IsActive = true, CategoryId = 28 },
new Product { ProductId = 276, ProductName = "Compostable Packaging Film", Description = "For wrapping products.", Price = 0.20m, Material = Material.Bioplastics, IsActive = true, CategoryId = 28 },
new Product { ProductId = 277, ProductName = "Custom Compostable Packaging", Description = "For branding needs.", Price = 0.30m, Material = Material.Bioplastics, IsActive = true, CategoryId = 28 },
new Product { ProductId = 278, ProductName = "Compostable Snack Bags", Description = "For snacks.", Price = 0.15m, Material = Material.Bioplastics, IsActive = true, CategoryId = 28 },
new Product { ProductId = 279, ProductName = "Compostable Food Wrap", Description = "For food storage.", Price = 0.20m, Material = Material.Bioplastics, IsActive = true, CategoryId = 28 },
new Product { ProductId = 280, ProductName = "Compostable Serving Trays", Description = "For catering.", Price = 0.25m, Material = Material.Bioplastics, IsActive = true, CategoryId = 28 },

new Product { ProductId = 281, ProductName = "E-commerce Shipping Boxes", Description = "For safe delivery.", Price = 1.00m, Material = Material.Paper, IsActive = true, CategoryId = 29 },
new Product { ProductId = 282, ProductName = "E-commerce Bubble Mailers", Description = "For fragile items.", Price = 0.80m, Material = Material.Paper, IsActive = true, CategoryId = 29 },
new Product { ProductId = 283, ProductName = "E-commerce Packaging Tape", Description = "For sealing boxes.", Price = 0.10m, Material = Material.Paper, IsActive = true, CategoryId = 29 },
new Product { ProductId = 284, ProductName = "E-commerce Void Fill", Description = "For cushioning items.", Price = 0.20m, Material = Material.Paper, IsActive = true, CategoryId = 29 },
new Product { ProductId = 285, ProductName = "E-commerce Labels", Description = "For shipping information.", Price = 0.05m, Material = Material.Paper, IsActive = true, CategoryId = 29 },
new Product { ProductId = 286, ProductName = "E-commerce Custom Boxes", Description = "For branding needs.", Price = 1.20m, Material = Material.Paper, IsActive = true, CategoryId = 29 },
new Product { ProductId = 287, ProductName = "E-commerce Packing Slips", Description = "For order details.", Price = 0.03m, Material = Material.Paper, IsActive = true, CategoryId = 29 },
new Product { ProductId = 288, ProductName = "E-commerce Mailing Tubes", Description = "For posters and art.", Price = 0.15m, Material = Material.Paper, IsActive = true, CategoryId = 29 },
new Product { ProductId = 289, ProductName = "E-commerce Bubble Wrap", Description = "For fragile items.", Price = 0.25m, Material = Material.Paper, IsActive = true, CategoryId = 29 },
new Product { ProductId = 290, ProductName = "E-commerce Gift Wrapping", Description = "For special occasions.", Price = 0.30m, Material = Material.Paper, IsActive = true, CategoryId = 29 },

new Product { ProductId = 291, ProductName = "Industrial Shrink Wrap", Description = "For securing large items.", Price = 0.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 30 },
new Product { ProductId = 292, ProductName = "Industrial Pallet Wrap", Description = "For bundling products.", Price = 1.00m, Material = Material.Polyethylene, IsActive = true, CategoryId = 30 },
new Product { ProductId = 293, ProductName = "Industrial Strapping", Description = "For securing loads.", Price = 0.30m, Material = Material.Polypropylene, IsActive = true, CategoryId = 30 },
new Product { ProductId = 294, ProductName = "Industrial Containers", Description = "For bulk storage.", Price = 1.50m, Material = Material.Polyethylene, IsActive = true, CategoryId = 30 },
new Product { ProductId = 295, ProductName = "Industrial Shipping Boxes", Description = "For heavy-duty shipping.", Price = 1.20m, Material = Material.Paper, IsActive = true, CategoryId = 30 },
new Product { ProductId = 296, ProductName = "Industrial Packaging Tape", Description = "For sealing boxes.", Price = 0.15m, Material = Material.Paper, IsActive = true, CategoryId = 30 },
new Product { ProductId = 297, ProductName = "Industrial Plastic Wrap", Description = "For protecting products.", Price = 0.40m, Material = Material.Polyethylene, IsActive = true, CategoryId = 30 },
new Product { ProductId = 298, ProductName = "Industrial Bags", Description = "For bulk materials.", Price = 0.25m, Material = Material.Polyethylene, IsActive = true, CategoryId = 30 },
new Product { ProductId = 299, ProductName = "Industrial Foam Inserts", Description = "For cushioning fragile items.", Price = 0.75m, Material = Material.Polyethylene, IsActive = true, CategoryId = 30 },
new Product { ProductId = 300, ProductName = "Custom Industrial Packaging", Description = "Tailored for specific needs.", Price = 1.80m, Material = Material.Polyethylene, IsActive = true, CategoryId = 30 }
    );
        }
    }
}
